.orig x0
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL TRAP_GETC
.FILL TRAP_OUT
.FILL TRAP_PUTS
.FILL TRAP_IN
.FILL TRAP_PUTSP
.FILL TRAP_HALT
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL EX_PRIV
.FILL EX_ILL
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
                ;X200
OS_START        LD R6, OS_SP
                LEA R0, OS_START_MSG
                PUTS
                LDI R0, OS_PSR
                LD R1, MASK_HI
                NOT R0, R0
                AND R0, R0, R1
                NOT R0, R0
                STI R0, OS_PSR
                HALT
OS_START_MSG    .STRINGZ ""
OS_KBSR         .FILL   XFE00
OS_KBDR         .FILL   XFE02
OS_DSR          .FILL   XFE04
OS_DDR          .FILL   XFE06
OS_PSR          .FILL   XFFFC
OS_MCR          .FILL   XFFFE
OS_SP           .FILL   X3000
MASK_HI         .FILL   X7FFF
LOW_8_BITS      .FILL   X00FF
TOUT_R1         .BLKW   #1
TIN_R7          .BLKW   #1
OS_R0           .BLKW   #1
OS_R1           .BLKW   #1
OS_R2           .BLKW   #1
OS_R3           .BLKW   #1
OS_R7           .BLKW   #1

TRAP_GETC       LDI R0, OS_KBSR
                BRZP TRAP_GETC
                LDI R0, OS_KBDR
                RET                 ;#RTI

TRAP_OUT        ST R1, TOUT_R1
TRAP_OUT_WAIT   LDI R1, OS_DSR
                BRZP TRAP_OUT_WAIT
                STI R0, OS_DDR
                LD R1, TOUT_R1
                RET                 ;#RTI
                
TRAP_PUTS       ST R0, OS_R0
                ST R1, OS_R1
                ST R7, OS_R7
                ADD R1, R0, #0
TRAP_PUTS_LOOP  LDR R0, R1, #0
                BRZ TRAP_PUTS_DONE
                OUT
                ADD R1, R1, #1
                BR TRAP_PUTS_LOOP
TRAP_PUTS_DONE  LD R0, OS_R0
                LD R1, OS_R1
                LD R7, OS_R7
                RET                 ;#RTI
                
TRAP_IN         ST R7, TIN_R7
                LEA R0, TRAP_IN_MSG
                PUTS
                GETC
                OUT
                ST R0, OS_R0
                AND R0, R0, #0
                ADD R0, R0, #10
                OUT
                LD R0, OS_R0
                LD R7, TIN_R7
                RET                 ;#RTI
                
TRAP_PUTSP      ST R0, OS_R0
                ST R1, OS_R1
                ST R2, OS_R2
                ST R3, OS_R3
                ST R7, OS_R7
                ADD R1, R0, #0
TRAP_PUTSP_LOOP LDR R2, R1, #0
                LD R0, LOW_8_BITS
                AND R0, R0, R2
                BRZ TRAP_PUTSP_DONE
                OUT
                AND R0, R0, #0
                ADD R3, R0, #8
TRAP_PUTSP_S_LOOP   ADD R0, R0, R0
                ADD R2, R2, #0
                BRZP TRAP_PUTSP_MSB_0
                ADD R0, R0, #1
TRAP_PUTSP_MSB_0    ADD R2, R2, R2
                ADD R3, R3, #-1
                BRP TRAP_PUTSP_S_LOOP
                ADD R0, R0, #0
                BRZ TRAP_PUTSP_DONE
                OUT
                ADD R1, R1, #1
                BRNZP TRAP_PUTSP_LOOP
TRAP_PUTSP_DONE LD R0, OS_R0
                LD R1, OS_R1
                LD R2, OS_R2
                LD R3, OS_R3
                LD R7, OS_R7
                RET                 ;#RTI
                
TRAP_HALT       LEA R0, TRAP_HALT_MSG
                PUTS
                LDI R0, OS_MCR
                LD R1, MASK_HI
                AND R0, R0, R1
                STI R0, OS_MCR
                BR TRAP_HALT
                
TRAP_PUSH       add r6, r6, #-1
                str r0, r6, #0
                ret

TRAP_POP        ldr r0, r6, #0
                add r6, r6, #1
                ret
                
TRAP_STK_OVRFLW LEA R0, TRAP_STKOVRFLW_MSG
                PUTS
                HALT

TRAP_STK_UDRFLW LEA R0, TRAP_STKUDRFLW_MSG
                PUTS
                HALT
                
BAD_TRAP        LEA R0, BAD_TRAP_MSG
                PUTS
                HALT
                
EX_PRIV         LEA R0, EX_PRIV_MSG
                PUTS
                HALT
                
EX_ILL          LEA R0, EX_ILL_MSG
                PUTS
                HALT
                
BAD_INT         RTI

TRAP_IN_MSG         .STRINGZ "\nInput a character> "
TRAP_HALT_MSG       .STRINGZ "\n\n--- Halting the LC-3 ---\n\n"
TRAP_STKOVRFLW_MSG  .stringz "\n\n--- Stack overflew ---\n\n"
TRAP_STKUDRFLW_MSG  .stringz "\n\n--- Stack underflew ---\n\n"
BAD_TRAP_MSG        .STRINGZ "\n\n--- Undefined trap executed ---\n\n"
EX_PRIV_MSG         .STRINGZ "\n\n--- Access violation ---\n\n"
EX_ILL_MSG          .STRINGZ "\n\n--- Illegal opcode ---\n\n"
.END



.orig x4180
st r1, POPPUSH_R1SVR
add r6, r6, #-1
ld r1, Top_Comp
add r1, r1, r6
brzp #1
trap x26
str r0, r6, #0
ld r1, POPPUSH_R1SVR
ret
st r1, POPPUSH_R1SVR
ld r1, Bott_Comp
add r1, r1, r6
brn #1
trap x27
ldr r0, r6, #0
add r6, r6, #1
ld r1, POPPUSH_R1SVR
ret
POPPUSH_R1SVR .blkw #1
Top_Comp .fill x-4000
Bott_Comp .fill x-4100
.end

.orig x0026
.fill x0400
.fill x0403
.end