.ORIG X0
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL TRAP_GETC
.FILL TRAP_OUT
.FILL TRAP_PUTS
.FILL TRAP_IN
.FILL TRAP_PUTSP
.FILL TRAP_HALT
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL TRAP_RRAM
.FILL TRAP_WRAM
.FILL TRAP_ERAM
.FILL TRAP_RAMRADDR
.FILL TRAP_RAMCADDR
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL EX_DIVISION_BY_ZERO
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL BAD_TRAP
.FILL EX_PRIV
.FILL EX_ILL
.FILL EX_TRAP_LOW_PRIORITY
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
.FILL BAD_INT
OS_START LD R6,OS_SP
LD R0,OS_INIT_PSR
ADD R6,R6,#-1
STR R0,R6,#0
LD R0,OS_INIT_PC
ADD R6,R6,#-1
STR R0,R6,#0
LEA R0,OS_START_MSG
PUTS
RTI
OS_START_MSG .STRINGZ "\n--- Welcome to LC-3 ---\n"
OS_KBSR .FILL XFE00
OS_KBDR .FILL XFE02
OS_DSR .FILL XFE04
OS_DDR .FILL XFE06
OS_RAMBR .FILL XFFE0
OS_RAMRA .FILL XFFEA
OS_RAMCA .FILL XFFEC
OS_RAMSR .FILL XFFEE
OS_PSR .FILL XFFFC
OS_MCR .FILL XFFFE
OS_INIT_PC .FILL X3000
OS_INIT_PSR .FILL X8001
OS_SP .FILL X3000
MASK_HI .FILL X7FFF
LOW_8_BITS .FILL X00FF
TRAM_EXECUTE .FILL XBFFF
TOUT_R1 .BLKW #1
TIN_R7 .BLKW #1
TRAM_R2 .BLKW #1
TRAM_R3 .BLKW #1
OS_R0 .BLKW #1
OS_R1 .BLKW #1
OS_R2 .BLKW #1
OS_R3 .BLKW #1
OS_R7 .BLKW #1
TRAP_GETC LDI R0,OS_KBSR
BRZP TRAP_GETC
LDI R0,OS_KBDR
RTI
TRAP_OUT ST R1,TOUT_R1
TRAP_OUT_WAIT LDI R1,OS_DSR
BRZP TRAP_OUT_WAIT
STI R0,OS_DDR
LD R1,TOUT_R1
RTI
TRAP_PUTS ST R0,OS_R0
ST R1,OS_R1
ST R7,OS_R7
ADD R1,R0,#0
TRAP_PUTS_LOOP LDR R0,R1,#0
BRZ TRAP_PUTS_DONE
OUT
ADD R1,R1,#1
BR TRAP_PUTS_LOOP
TRAP_PUTS_DONE LD R0,OS_R0
LD R1,OS_R1
LD R7,OS_R7
RTI
TRAP_IN ST R7,TIN_R7
LEA R0,TRAP_IN_MSG
PUTS
GETC
OUT
ST R0,OS_R0
AND R0,R0,#0
ADD R0,R0,#10
OUT
LD R0,OS_R0
LD R7,TIN_R7
RTI
TRAP_PUTSP ST R0,OS_R0
ST R1,OS_R1
ST R2,OS_R2
ST R3,OS_R3
ST R7,OS_R7
ADD R1,R0,#0
TRAP_PUTSP_LOOP LDR R2,R1,#0
LD R0,LOW_8_BITS
AND R0,R0,R2
BRZ TRAP_PUTSP_DONE
OUT
AND R0,R0,#0
ADD R3,R0,#8
TRAP_PUTSP_S_LOOP ADD R0,R0,R0
ADD R2,R2,#0
BRZP TRAP_PUTSP_MSB_0
ADD R0,R0,#1
TRAP_PUTSP_MSB_0 ADD R2,R2,R2
ADD R3,R3,#-1
BRP TRAP_PUTSP_S_LOOP
ADD R0,R0,#0
BRZ TRAP_PUTSP_DONE
OUT
ADD R1,R1,#1
BRNZP TRAP_PUTSP_LOOP
TRAP_PUTSP_DONE LD R0,OS_R0
LD R1,OS_R1
LD R2,OS_R2
LD R3,OS_R3
LD R7,OS_R7
RTI
TRAP_HALT LEA R0,TRAP_HALT_MSG
PUTS
LDI R0,OS_MCR
LD R1,MASK_HI
AND R0,R0,R1
STI R0,OS_MCR
BR TRAP_HALT
TRAP_RRAM ST R2, TRAM_R2
LDI R2, OS_RAMSR
BRN #-2
LD R2, OS_RAMBR
ADD R2, R2, R1
LDR R0, R2, #0
LD R2, TRAM_R2
RTI
TRAP_WRAM ST R2, TRAM_R2
LDI R2, OS_RAMSR
BRN #-2
LD R2, OS_RAMBR
ADD R2, R2, R1
STR R0, R2, #0
LD R2, TRAM_R2
RTI
TRAP_ERAM ST R2, TRAM_R2
ST R3, TRAM_R3
LDI R2, OS_RAMSR
BRN #-2
LDI R3, TRAM_EXECUTE
AND R2, R2, R3
STI R2, OS_RAMSR
LD R2, TRAM_R2
LD R3, TRAM_R3
RTI
TRAP_RAMRADDR ST R2, TRAM_R2
LDI R2, OS_RAMSR
BRN #-2
STI R0, OS_RAMRA
LD R2, TRAM_R2
RTI
TRAP_RAMCADDR ST R2, TRAM_R2
LDI R2, OS_RAMSR
BRN #-2
STI R0, OS_RAMCA
LD R2, TRAM_R2
RTI
EX_DIVISION_BY_ZERO LEA R0, EX_DIVISION_BY_ZERO_MSG
PUTS
HALT

BAD_TRAP LEA R0,BAD_TRAP_MSG
PUTS
HALT
EX_PRIV LEA R0,EX_PRIV_MSG
PUTS
HALT
EX_ILL LEA R0,EX_ILL_MSG
PUTS
HALT
EX_TRAP_LOW_PRIORITY LEA R0, EX_TRAP_LOW_PRIORITY_MSG
PUTS
HALT
BAD_INT RTI
EX_DIVISION_BY_ZERO_MSG .STRINGZ "\n--- Division By Zero ---\n\n"
TRAP_IN_MSG .STRINGZ "\nInput a character> "
TRAP_HALT_MSG .STRINGZ "\n\n--- Halting the LC-3 ---\n\n"
BAD_TRAP_MSG .STRINGZ "\n\n--- Undefined trap executed ---\n\n"
EX_PRIV_MSG .STRINGZ "\n\n--- Access violation ---\n\n"
EX_ILL_MSG .STRINGZ "\n\n--- Illegal opcode ---\n\n"
EX_TRAP_LOW_PRIORITY_MSG .STRINGZ "\n\n--- Cannot execute TRAPs during Interrupts ---\n\n"
.END
